language: ruby
sudo: false
install: bundle install --without development --jobs=3 --retry=3
cache:
  directories:
  - bundle
branches:
  only:
  - build
env:
  global:
    - SITE_ENV=deploy
rvm:
  - 2.3.0
before_script:
- git config --global user.email "antondavyodv.o@gmail.com"
- git config --global user.name "Anton Davydov"
- git remote rm origin
- git remote add origin https://davydovanton:${GH_TOKEN}@github.com/hanami/hanami.github.io.git
- mkdir build
script:
- bundle exec middleman build && bundle exec middleman deploy
env:
  global:
  - secure: c4G+9Fx0Sqf9TiWWACu6GQ93wHqGFm8p0bB7hCyKHVdqCD0NPxllyln7cr2BAQiB3qTzhGejr9Ghe2BgMOnDfmsCryGcIrfolarCim54HNsponJRtZNru0KKGNsfplbpAToZhfGJ+zNq2suJKx4AUmqIgp0ecpju1LkHOeE3fwk=
