language: ruby
sudo: false
install: bundle install --without development --jobs=3 --retry=3
cache:
  directories:
  - bundle
branches:
  only:
  - build
env:
  global:
    - SITE_ENV=deploy
rvm:
  - 2.3.0
before_script:
- git config --global user.email "trung.le@ruby-journal.com"
- git config --global user.name "Trung Lê"
- git remote rm origin
- git remote add origin https://joneslee85:${GH_TOKEN}@github.com/hanami/hanami.github.io.git
- mkdir build
script:
- bundle exec middleman build && bundle exec middleman deploy
env:
  global:
  - secure: YZlMVMMZ9fLE4enTCfoaeajmbcCbnECe6v3FmkhKx4K/AMp3fkSk+bYOl/rfCf7hXKV4Fk1MUCU6X/gz93P/DpW88R9Dr+7iFsJpVJd5+by7xFcHri1j22eTJ0ODgxyGcDZoSYzlVbecO1sYgTFsmNO1v4Lhyx7ALjBAEKH1aAM=
