language: ruby
sudo: false
cache: bundler
install: true
branches:
  only:
  - build
env:
  global:
    - SITE_ENV=deploy
before_script:
- bundle install
- git config --global user.email "trung.le@ruby-journal.com"
- git config --global user.name "Trung Lê"
- git remote rm origin
- git remote add origin https://joneslee85:${GH_TOKEN}@github.com/hanami/hanami.github.io.git
- mkdir build
script: "./bin/site publish"
env:
  global:
  - secure: YZlMVMMZ9fLE4enTCfoaeajmbcCbnECe6v3FmkhKx4K/AMp3fkSk+bYOl/rfCf7hXKV4Fk1MUCU6X/gz93P/DpW88R9Dr+7iFsJpVJd5+by7xFcHri1j22eTJ0ODgxyGcDZoSYzlVbecO1sYgTFsmNO1v4Lhyx7ALjBAEKH1aAM=
